apiVersion: v1
kind: Namespace
metadata:
  name: croak01
---
apiVersion: v1
kind: Pod
metadata:
  name: ingest-api
  namespace: croak01
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_OUT
        value: "ingest.api"
    name: busybox
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: parse-api
  namespace: croak01
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_IN
        value: "ingest.api"
      - name: KAFKA_OUT
        value: "parse.api"
    name: busybox
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: export-api
  namespace: croak01
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_IN
        value: "parse.api"
      - name: KAFKA_OUT
        value: "export.api"
    name: busybox
  restartPolicy: Always
